@Hiscox.RaterApiWrapper.Presentation.Api_HostAddress = https://localhost:7293

POST {{Hiscox.RaterApiWrapper.Presentation.Api_HostAddress}}/api/rater/
Accept: application/json
Content-Type: application/json
{
  "Product": "ArchitectureAndEngineering",
  "PolicyNumber": "5064044",
  "BusinessType": "Renewal",
  "Revenue": 80000,
  "Coverages": [
    {
      "CoverageType": "EAndOPrimary",
      "OccuranceLimit": 1000000,
      "AggregateLimit": 3000000,
      "Retention": 2500
    }
  ],
  "IndustryClassifications": [
    {
      "Sector": "Design Professionals",
      "SubSector": "Architectural Services",
      "Specialty": "Architectural Services",
      "PercentageExposure": 1
    }
  ],
  "AdditionalRiskProfile": {
    "EnvironmentalRemediation": false,
    "UndergroundUtilityLocators": false,
    "Nuclear": false,
    "Offshore": false,
    "Superfund": false,
    "UndergroundStorage": false,
    "ZipLines": false,
    "AmusementParks": false,
    "Prototypes": false,
    "TangibleGoodsOrProduct": false,
    "ProjectTypes": [
      "Commercial",
      "ResidentialAndApartments"
    ]
  },
  "ClaimsHistory": null,
  "OptionalEnhancements": [
    {
      "OptionalEnhancementName": "Crisis Management",
      "OptionalEnhancementValue": "50000"
    },
    {
      "OptionalEnhancementName": "Media activities",
      "OptionalEnhancementValue": "Full"
    }
  ]
}

###
