// <auto-generated />
using System;
using Hiscox.RaterApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hiscox.RaterApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.BusinessSizeDefinition", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CoverageType")
                        .HasColumnType("integer")
                        .HasColumnName("coverage_type");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("revenue");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.HasKey("Version", "Id")
                        .HasName("pk_business_size_definitions");

                    b.ToTable("business_size_definitions", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.DataValidation", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DataValidationToUse")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("data_validation_to_use");

                    b.Property<string>("Peril")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("peril");

                    b.HasKey("Version", "Id")
                        .HasName("pk_data_validations");

                    b.ToTable("data_validations", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.DisplayedDefaultPeril", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ApplicableTo")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("applicable_to");

                    b.Property<string>("DefaultPeril")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("default_peril");

                    b.Property<string>("DefaultValueWhenSwitchedOn")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("default_value_when_switched_on");

                    b.Property<bool>("IsSwitchedOnByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_switched_on_by_default");

                    b.HasKey("Version", "Id")
                        .HasName("pk_displayed_default_perils");

                    b.ToTable("displayed_default_perils", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.Form", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Version", "Id")
                        .HasName("pk_forms");

                    b.ToTable("forms", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.FormEligibility", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("IndustrySpecialtyId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_specialty_id");

                    b.Property<int>("FormId")
                        .HasColumnType("integer")
                        .HasColumnName("form_id");

                    b.HasKey("Version", "IndustrySpecialtyId", "FormId")
                        .HasName("pk_form_eligibilities");

                    b.HasIndex("Version", "FormId")
                        .HasDatabaseName("ix_form_eligibilities_version_form_id");

                    b.ToTable("form_eligibilities", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.FormInfoLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageEnhancements")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("coverage_enhancements");

                    b.Property<string>("DefaultClaimBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("default_claim_basis");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("form_name");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("line_of_business");

                    b.Property<string>("LineOfBusinessShort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("line_of_business_short");

                    b.HasKey("Id")
                        .HasName("pk_form_info_lookups");

                    b.ToTable("form_info_lookups", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.GeographicMod", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("AE")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("ae");

                    b.Property<decimal>("Ahc")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("ahc");

                    b.Property<string>("CountyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(3)")
                        .HasColumnName("county_number");

                    b.Property<decimal>("Cyber")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("cyber");

                    b.Property<string>("Fips")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("fips");

                    b.Property<decimal>("GlPremOps")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("gl_prem_ops");

                    b.Property<decimal>("GlProducts")
                        .HasColumnType("numeric")
                        .HasColumnName("gl_products");

                    b.Property<decimal>("Med")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("med");

                    b.Property<decimal>("Mpl")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("mpl");

                    b.Property<string>("MsaName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("msa_name");

                    b.Property<string>("MsaNumber")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("msa_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state");

                    b.Property<decimal>("Tech")
                        .HasColumnType("decimal(20, 15)")
                        .HasColumnName("tech");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasColumnName("zip");

                    b.HasKey("Version", "Id")
                        .HasName("pk_geographic_mods");

                    b.ToTable("geographic_mods", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IncludedCoverageEnhancements", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ClaimsMode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("claims_mode");

                    b.Property<string>("CoverageEnhancements")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("coverage_enhancements");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("form");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("line_of_business");

                    b.Property<string>("ShortenedLineOfBusiness")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("shortened_line_of_business");

                    b.HasKey("Version", "Id")
                        .HasName("pk_included_coverage_enhancements");

                    b.ToTable("included_coverage_enhancements", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustryModifier", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("EOMinimumPremium")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("eo_minimum_premium");

                    b.Property<decimal>("NAICSModifier")
                        .HasColumnType("decimal(18,15)")
                        .HasColumnName("naics_modifier");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("specialty");

                    b.HasKey("Version", "Id")
                        .HasName("pk_industry_modifiers");

                    b.ToTable("industry_modifiers", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Version", "Id")
                        .HasName("pk_industry_sectors");

                    b.ToTable("industry_sectors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("IndustrySubSectorId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_sub_sector_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Version", "Id")
                        .HasName("pk_industry_specialties");

                    b.HasIndex("Version", "IndustrySubSectorId")
                        .HasDatabaseName("ix_industry_specialties_version_industry_sub_sector_id");

                    b.ToTable("industry_specialties", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySubSector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("IndustrySectorId")
                        .HasColumnType("integer")
                        .HasColumnName("industry_sector_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Version", "Id")
                        .HasName("pk_industry_sub_sectors");

                    b.HasIndex("Version", "IndustrySectorId")
                        .HasDatabaseName("ix_industry_sub_sectors_version_industry_sector_id");

                    b.ToTable("industry_sub_sectors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.LimitRetentionFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal?>("EoHigh")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("eo_high");

                    b.Property<decimal?>("EoLow")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("eo_low");

                    b.Property<decimal?>("EoMedium")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("eo_medium");

                    b.Property<decimal?>("FactorCyber")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor_cyber");

                    b.Property<decimal?>("FactorGlPremisesOperations")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor_gl_premises_operations");

                    b.Property<decimal?>("FactorGlProductsOperations")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor_gl_products_operations");

                    b.Property<long?>("LimitRetentionOption")
                        .HasColumnType("bigint")
                        .HasColumnName("limit_retention_option");

                    b.HasKey("Version", "Id")
                        .HasName("pk_limit_retention_factors");

                    b.ToTable("limit_retention_factors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptCovTable1", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ApplicableToCoverageOrGTC")
                        .IsRequired()
                        .HasColumnType("varchar(15)")
                        .HasColumnName("applicable_to_coverage_or_gtc");

                    b.Property<string>("ApplicableToFormOrEndorsement")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasColumnName("applicable_to_form_or_endorsement");

                    b.Property<string>("ENumber")
                        .IsRequired()
                        .HasColumnType("varchar(25)")
                        .HasColumnName("e_number");

                    b.Property<string>("OptionalCoverage")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("optional_coverage");

                    b.HasKey("Version", "Id")
                        .HasName("pk_opt_cov_table1");

                    b.ToTable("opt_cov_table1", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalAdditionalCoverageFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("coverage");

                    b.Property<decimal>("MaterialFactor")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("material_factor");

                    b.Property<decimal>("MinimalFactor")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("minimal_factor");

                    b.Property<decimal>("YesFactor")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("yes_factor");

                    b.HasKey("Version", "Id")
                        .HasName("pk_optional_additional_coverage_factors");

                    b.ToTable("optional_additional_coverage_factors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalCoverageFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("factor");

                    b.Property<decimal>("PercentOfOccLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("percent_of_occ_limit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.HasKey("Version", "Id")
                        .HasName("pk_optional_coverage_factors");

                    b.ToTable("optional_coverage_factors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalCoveragesTable1", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("OptionalAdditionalCoverage")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("optional_additional_coverage");

                    b.Property<string>("Premium")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("premium");

                    b.Property<string>("ValueOfInsurance")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("value_of_insurance");

                    b.HasKey("Version", "Id")
                        .HasName("pk_optional_coverages_table1");

                    b.ToTable("optional_coverages_table1", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalCoveragesTable2", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("varchar(55)")
                        .HasColumnName("coverage");

                    b.Property<string>("Differential")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("differential");

                    b.HasKey("Version", "Id")
                        .HasName("pk_optional_coverages_table2");

                    b.ToTable("optional_coverages_table2", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.PolicyDetails", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("Cyb_AggLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("cyb__agg_limit");

                    b.Property<decimal>("Cyb_GWP")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("cyb_gwp");

                    b.Property<decimal>("Cyb_OccLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("cyb__occ_limit");

                    b.Property<decimal>("Cyb_Retention")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("cyb__retention");

                    b.Property<decimal>("EO_2_AggLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo_2__agg_limit");

                    b.Property<decimal>("EO_2_GWP")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo_2_gwp");

                    b.Property<decimal>("EO_2_OccLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo_2__occ_limit");

                    b.Property<decimal>("EO_2_Retention")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo_2__retention");

                    b.Property<decimal>("EO_AggLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo__agg_limit");

                    b.Property<decimal>("EO_GWP")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo_gwp");

                    b.Property<decimal>("EO_OccLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo__occ_limit");

                    b.Property<decimal>("EO_Retention")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("eo__retention");

                    b.Property<decimal>("ExposureBase")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("exposure_base");

                    b.Property<decimal>("GL_AggLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gl__agg_limit");

                    b.Property<decimal>("GL_GWP")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gl_gwp");

                    b.Property<decimal>("GL_OccLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gl__occ_limit");

                    b.Property<decimal>("GL_Retention")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("gl__retention");

                    b.Property<string>("NameDescr")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name_descr");

                    b.Property<string>("PUID")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("puid");

                    b.Property<string>("PolicyNo")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_no");

                    b.Property<DateTime>("TimestampEffectivePolicy")
                        .HasColumnType("timestamp")
                        .HasColumnName("timestamp_effective_policy");

                    b.Property<DateTime>("TimestampExpirationPolicy")
                        .HasColumnType("timestamp")
                        .HasColumnName("timestamp_expiration_policy");

                    b.Property<string>("Zip")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("zip");

                    b.HasKey("Version", "Id")
                        .HasName("pk_policies");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.ProjectTypeFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("factor");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("project_type");

                    b.HasKey("Version", "Id")
                        .HasName("pk_project_type_factors");

                    b.ToTable("project_type_factors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RatingFactorMaster", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("Answer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("answer");

                    b.Property<string>("DegreeOfConcern")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("degree_of_concern");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("factor");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("high");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("low");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.HasKey("Version", "Id")
                        .HasName("pk_rating_factor_master");

                    b.ToTable("rating_factor_master", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RatingFactorSectionEnability", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<int>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("integer")
                        .HasColumnName("section");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.HasKey("Version", "Id")
                        .HasName("pk_rating_factor_section_enabilities");

                    b.ToTable("rating_factor_section_enabilities", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RetainedValueFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor");

                    b.Property<int>("RetainedValuePercent")
                        .HasColumnType("int")
                        .HasColumnName("retained_value_percent");

                    b.HasKey("Version", "Id")
                        .HasName("pk_retained_value_factors");

                    b.ToTable("retained_value_factors", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RetainedValueFactorMatrix", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("FactorCyber")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor_cyber");

                    b.Property<decimal>("FactorEO")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor_eo");

                    b.Property<decimal>("FactorGL")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("factor_gl");

                    b.Property<decimal>("RetainedValue")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("retained_value");

                    b.HasKey("Version", "Id")
                        .HasName("pk_retained_value_factor_matrix");

                    b.ToTable("retained_value_factor_matrix", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RevenueBaseRate", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("version");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseRateAHC")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate_ahc");

                    b.Property<decimal>("BaseRateCyber")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate_cyber");

                    b.Property<decimal>("BaseRateEO")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate_eo");

                    b.Property<decimal>("BaseRateHomeHealthcare")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate_home_healthcare");

                    b.Property<decimal>("BaseRateSpas")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate_spas");

                    b.Property<decimal>("BaseRateTechEO")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("base_rate_tech_eo");

                    b.Property<decimal>("GLPremisesOperations1")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("gl_premises_operations1");

                    b.Property<decimal>("GLPremisesOperations2")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("gl_premises_operations2");

                    b.Property<int?>("Revenue")
                        .HasColumnType("integer")
                        .HasColumnName("revenue");

                    b.HasKey("Version", "Id")
                        .HasName("pk_revenue_base_rates");

                    b.ToTable("revenue_base_rates", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.FormEligibility", b =>
                {
                    b.HasOne("Hiscox.RaterApi.Domain.Entities.Form", null)
                        .WithMany()
                        .HasForeignKey("Version", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_eligibilities_forms_version_form_id");

                    b.HasOne("Hiscox.RaterApi.Domain.Entities.IndustrySpecialty", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_eligibilities__industry_specialties_version_industry_spe~");
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.HasOne("Hiscox.RaterApi.Domain.Entities.IndustrySubSector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySubSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_industry_specialties__industry_sub_sectors_version_industry_su~");
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySubSector", b =>
                {
                    b.HasOne("Hiscox.RaterApi.Domain.Entities.IndustrySector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_industry_sub_sectors_industry_sectors_version_industry_sect~");
                });
#pragma warning restore 612, 618
        }
    }
}
