// <auto-generated />
using System;
using Hiscox.RaterApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiscox.RaterApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.BusinessSizeDefinition", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CoverageType")
                        .HasColumnType("int");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Version", "Id");

                    b.ToTable("BusinessSizeDefinition", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.DataValidation", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DataValidationToUse")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Peril")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Version", "Id");

                    b.ToTable("DataValidations", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.DisplayedDefaultPeril", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApplicableTo")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("DefaultPeril")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("DefaultValueWhenSwitchedOn")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<bool>("IsSwitchedOnByDefault")
                        .HasColumnType("bit");

                    b.HasKey("Version", "Id");

                    b.ToTable("DisplayedDefaultPerils", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.Form", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.FormEligibility", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("IndustrySpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.HasKey("Version", "IndustrySpecialtyId", "FormId");

                    b.HasIndex("Version", "FormId");

                    b.ToTable("FormEligibility", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.FormInfoLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageEnhancements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultClaimBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LineOfBusinessShort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("FormInfoLookup", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.GeographicMod", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AE")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("Ahc")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("CountyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("Cyber")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("Fips")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("GlPremOps")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("GlProducts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Med")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("Mpl")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("MsaName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MsaNumber")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("Tech")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Version", "Id");

                    b.ToTable("GeographicMod", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IncludedCoverageEnhancements", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClaimsMode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CoverageEnhancements")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("ShortenedLineOfBusiness")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Version", "Id");

                    b.ToTable("IncludedCoverageEnhancements", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustryModifier", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("EOMinimumPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NAICSModifier")
                        .HasColumnType("decimal(18,15)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("IndustryModifier", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("IndustrySector", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IndustrySubSectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.HasIndex("Version", "IndustrySubSectorId");

                    b.ToTable("IndustrySpecialty", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySubSector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IndustrySectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.HasIndex("Version", "IndustrySectorId");

                    b.ToTable("IndustrySubSector", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.LimitRetentionFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal?>("EoHigh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EoLow")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("EoMedium")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FactorCyber")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FactorGlPremisesOperations")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FactorGlProductsOperations")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("LimitRetentionOption")
                        .HasColumnType("bigint");

                    b.HasKey("Version", "Id");

                    b.ToTable("LimitRetentionFactor", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptCovTable1", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApplicableToCoverageOrGTC")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ApplicableToFormOrEndorsement")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ENumber")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("OptionalCoverage")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Version", "Id");

                    b.ToTable("OptCovTable1", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalAdditionalCoverageFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("MaterialFactor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinimalFactor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("YesFactor")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Version", "Id");

                    b.ToTable("OptionalAdditionalCoverageFactor", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalCoverageFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PercentOfOccLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("OptionalCoverageFactor", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalCoveragesTable1", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("OptionalAdditionalCoverage")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Premium")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("ValueOfInsurance")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.HasKey("Version", "Id");

                    b.ToTable("OptionalCoverageTable1", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.OptionalCoveragesTable2", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasColumnType("varchar(55)");

                    b.Property<string>("Differential")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Version", "Id");

                    b.ToTable("OptionalCoveragesTable2s", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.PolicyDetails", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Cyb_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Cyb_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Cyb_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Cyb_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ExposureBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NameDescr")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PUID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PolicyNo")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TimestampEffectivePolicy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampExpirationPolicy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Version", "Id");

                    b.ToTable("PolicyDetails", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.ProjectTypeFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("ProjectTypeFactor", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RatingFactorMaster", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Answer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("DegreeOfConcern")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Version", "Id");

                    b.ToTable("RatingFactorMaster", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RatingFactorSectionEnability", b =>
                {
                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<int>("Section")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Version", "Id");

                    b.ToTable("RatingFactorSectionEnability", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RetainedValueFactor", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RetainedValuePercent")
                        .HasColumnType("int");

                    b.HasKey("Version", "Id");

                    b.ToTable("RetainedValueFactor", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RetainedValueFactorMatrix", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("FactorCyber")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FactorEO")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FactorGL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RetainedValue")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Version", "Id");

                    b.ToTable("RetainedValueFactorMatrix", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.RevenueBaseRate", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseRateAHC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BaseRateCyber")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BaseRateEO")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BaseRateHomeHealthcare")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BaseRateSpas")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BaseRateTechEO")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GLPremisesOperations1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GLPremisesOperations2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Revenue")
                        .HasColumnType("int");

                    b.HasKey("Version", "Id");

                    b.ToTable("RevenueBaseRate", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.FormEligibility", b =>
                {
                    b.HasOne("Hiscox.RaterApi.Domain.Entities.Form", null)
                        .WithMany()
                        .HasForeignKey("Version", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hiscox.RaterApi.Domain.Entities.IndustrySpecialty", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.HasOne("Hiscox.RaterApi.Domain.Entities.IndustrySubSector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySubSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hiscox.RaterApi.Domain.Entities.IndustrySubSector", b =>
                {
                    b.HasOne("Hiscox.RaterApi.Domain.Entities.IndustrySector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
