// <auto-generated />
using System;
using Hiscox.RaterApiWrapper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiscox.RaterApiWrapper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.Form", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("Form", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.FormEligibility", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("IndustrySpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.HasKey("Version", "IndustrySpecialtyId", "FormId");

                    b.HasIndex("Version", "FormId");

                    b.ToTable("FormEligibility", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.FormInfoLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverageEnhancements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultClaimBasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LineOfBusiness")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LineOfBusinessShort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("FormInfoLookup", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.GeographicMod", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AE")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("Ahc")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("CountyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("Cyber")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("Fips")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("GlPremOps")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("GlProducts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Med")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("Mpl")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("MsaName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MsaNumber")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("Tech")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Version", "Id");

                    b.ToTable("GeographicMod", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("IndustrySector", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IndustrySubSectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.HasIndex("Version", "IndustrySubSectorId");

                    b.ToTable("IndustrySpecialty", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySubSector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IndustrySectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.HasIndex("Version", "IndustrySectorId");

                    b.ToTable("IndustrySubSector", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.PolicyDetails", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Cyb_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Cyb_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Cyb_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Cyb_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_2_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("EO_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ExposureBase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_AggLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_GWP")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_OccLimit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GL_Retention")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NameDescr")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PUID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PolicyNo")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TimestampEffectivePolicy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimestampExpirationPolicy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .HasColumnType("varchar(5)");

                    b.HasKey("Version", "Id");

                    b.ToTable("PolicyDetails", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.FormEligibility", b =>
                {
                    b.HasOne("Hiscox.RaterApiWrapper.Domain.Entities.Form", null)
                        .WithMany()
                        .HasForeignKey("Version", "FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySpecialty", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.HasOne("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySubSector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySubSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySubSector", b =>
                {
                    b.HasOne("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
