// <auto-generated />
using Hiscox.RaterApiWrapper.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hiscox.RaterApiWrapper.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.GeographicMod", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("AE")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("Ahc")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("CountyNumber")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("Cyber")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("Fips")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("GlPremOps")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("GlProducts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Med")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<decimal>("Mpl")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("MsaName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MsaNumber")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<decimal>("Tech")
                        .HasColumnType("decimal(20, 15)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Version", "Id");

                    b.ToTable("GeographicMod", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.ToTable("IndustrySector", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IndustrySubSectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.HasIndex("Version", "IndustrySubSectorId");

                    b.ToTable("IndustrySpecialty", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySubSector", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IndustrySectorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Version", "Id");

                    b.HasIndex("Version", "IndustrySectorId");

                    b.ToTable("IndustrySubSector", (string)null);
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySpecialty", b =>
                {
                    b.HasOne("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySubSector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySubSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySubSector", b =>
                {
                    b.HasOne("Hiscox.RaterApiWrapper.Domain.Entities.IndustrySector", null)
                        .WithMany()
                        .HasForeignKey("Version", "IndustrySectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
